# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-21 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('cs_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('segment', models.CharField(max_length=20)),
                ('account_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher_admin.AccountManager')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('aid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('logoUrl', models.CharField(blank=True, max_length=50)),
                ('homepageUrl', models.CharField(max_length=200)),
                ('integrationType', models.CharField(max_length=200)),
                ('parentOrg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher_admin.Organization')),
            ],
        ),
    ]
